/*
  Warnings:

  - The values [EQUITY_BANKING_AND_FINANCIAL_SERVICES] on the enum `FundCategory` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "FundCategory_new" AS ENUM ('HYBRID_DYNAMIC_ASSET_ALLOCATION', 'HYBRID_MULTI_ASSET_ALLOCATION', 'HYBRID_ARBITRAGE', 'HYBRID_AGGRESSIVE', 'HYBRID_CONSERVATIVE', 'HYBRID_EQUITY_SAVINGS', 'EQUITY_ELSS', 'EQUITY_FOCUSED', 'EQUITY_DIVIDEND_YIELD', 'EQUITY_SECTORAL_BANKING_AND_FINANCIAL_SERVICES', 'EQUITY_SECTORAL_TECHNOLOGY', 'EQUITY_SECTORAL_INFRASTRUCTURE', 'EQUITY_SECTORAL_PHARMA_AND_HEALTHCARE', 'EQUITY_THEMATIC_CONSUMPTION', 'EQUITY_THEMATIC_INTERNATIONAL', 'EQUITY_THEMATIC_MANUFACTURING', 'EQUITY_THEMATIC_TRANSPORTATION', 'EQUITY_THEMATIC_MNC', 'EQUITY_THEMATIC_PSU', 'EQUITY_THEMATIC_QUANTITATIVE', 'EQUITY_THEMATIC_ESG', 'EQUITY_THEMATIC_OTHERS', 'EQUITY_VALUE', 'EQUITY_FLEXI_CAP', 'EQUITY_LARGE_AND_MID_CAP', 'EQUITY_SMALL_CAP', 'EQUITY_MID_CAP', 'EQUITY_LARGE_CAP', 'EQUITY_MULTI_CAP', 'DEBT_DYNAMIC_BOND', 'DEBT_CORPORATE_BOND', 'DEBT_BANKING_AND_PSU', 'DEBT_LIQUID', 'DEBT_FLOATER', 'DEBT_GILT', 'DEBT_GILT_10_YEARS_CONSTANT', 'DEBT_MONEY_MARKET', 'DEBT_CREDIT_RISK', 'DEBT_MEDIUM_TO_LONG_DURATION', 'DEBT_LONG_DURATION', 'DEBT_LOW_DURATION', 'DEBT_MEDIUM_DURATION', 'DEBT_OVERNIGHT', 'DEBT_SHORT_DURATION', 'DEBT_ULTRA_SHORT_DURATION', 'FOF_DOMESTIC_DEBT', 'FOF_DOMESTIC_HYBRID', 'FOF_DOMESTIC_EQUITY', 'FOF_DOMESTIC_GOLD', 'FOF_DOMESTIC_SILVER', 'FOF_OVERSEAS', 'CHILDRENS_FUND', 'RETIREMENT_FUND', 'ETF', 'INDEX_FUND');
ALTER TABLE "Fund" ALTER COLUMN "category" TYPE "FundCategory_new" USING ("category"::text::"FundCategory_new");
ALTER TYPE "FundCategory" RENAME TO "FundCategory_old";
ALTER TYPE "FundCategory_new" RENAME TO "FundCategory";
DROP TYPE "FundCategory_old";
COMMIT;
