version: '3.8'
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    container_name: postfoo-db
    image: postgres:13.7
    restart: always
    environment:
      - POSTGRES_USER=postfoo
      - POSTGRES_PASSWORD=postfoo
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
