/* IMP NOTE: This file is auto-generated by npm run gql:codegen, don't change manually */
/* eslint-disable */
import * as t from 'src/types'
import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';
import type { GraphQLContext } from 'src/types';
export type RequireFields<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };


export type ResolverTypeWrapper<T> = Promise<T> | T;

export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> = ResolverFn<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = {}, TContext = {}, TArgs = {}> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
  parent: TParent,
  context: TContext,
  info?: GraphQLResolveInfo
) => t.Maybe<TTypes> | Promise<t.Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = {}, TContext = {}> = (obj: T, context: TContext, info?: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs = {}> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => TResult | Promise<TResult>;


/** Mapping of interface types */
export type ResolversInterfaceTypes<_RefType extends Record<string, unknown>> = {
  Node: ( t.Code ) | ( t.Field ) | ( t.Fund ) | ( t.Membership ) | ( t.Portfolio ) | ( t.PortfolioFund ) | ( t.PortfolioStock ) | ( t.Stock ) | ( t.User );
  PagePayload: ( t.FundsPayload ) | ( t.PortfolioFundsPayload ) | ( t.PortfolioStocksPayload ) | ( t.StocksPayload );
};

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = {
  BigInt: ResolverTypeWrapper<t.Scalars['BigInt']['output']>;
  Boolean: ResolverTypeWrapper<t.Scalars['Boolean']['output']>;
  Code: ResolverTypeWrapper<t.Code>;
  CreateFieldInput: t.CreateFieldInput;
  CreateFundInput: t.CreateFundInput;
  CreatePortfolioFundInput: t.CreatePortfolioFundInput;
  CreatePortfolioInput: t.CreatePortfolioInput;
  CreatePortfolioStockInput: t.CreatePortfolioStockInput;
  CreateStockInput: t.CreateStockInput;
  Date: ResolverTypeWrapper<t.Scalars['Date']['output']>;
  DateTime: ResolverTypeWrapper<t.Scalars['DateTime']['output']>;
  DeleteFieldInput: t.DeleteFieldInput;
  DeleteFundInput: t.DeleteFundInput;
  DeletePortfolioFundInput: t.DeletePortfolioFundInput;
  DeletePortfolioInput: t.DeletePortfolioInput;
  DeletePortfolioStockInput: t.DeletePortfolioStockInput;
  DeleteStockInput: t.DeleteStockInput;
  EmailAddress: ResolverTypeWrapper<t.Scalars['EmailAddress']['output']>;
  ErrorCode: t.ErrorCode;
  Exchange: t.Exchange;
  Field: ResolverTypeWrapper<t.Field>;
  FieldsInput: t.FieldsInput;
  Float: ResolverTypeWrapper<t.Scalars['Float']['output']>;
  ForgotPasswordInput: t.ForgotPasswordInput;
  Fund: ResolverTypeWrapper<t.Fund>;
  FundCategory: t.FundCategory;
  FundPlan: t.FundPlan;
  FundType: t.FundType;
  FundsInput: t.FundsInput;
  FundsPayload: ResolverTypeWrapper<t.FundsPayload>;
  ID: ResolverTypeWrapper<t.Scalars['ID']['output']>;
  Int: ResolverTypeWrapper<t.Scalars['Int']['output']>;
  JWT: ResolverTypeWrapper<t.Scalars['JWT']['output']>;
  Json: ResolverTypeWrapper<t.Scalars['Json']['output']>;
  JsonObject: ResolverTypeWrapper<t.Scalars['JsonObject']['output']>;
  Membership: ResolverTypeWrapper<t.Membership>;
  Mutation: ResolverTypeWrapper<undefined>;
  Node: ResolverTypeWrapper<ResolversInterfaceTypes<ResolversTypes>['Node']>;
  NonEmptyString: ResolverTypeWrapper<t.Scalars['NonEmptyString']['output']>;
  PageInfo: ResolverTypeWrapper<t.PageInfo>;
  PageInput: t.PageInput;
  PagePayload: ResolverTypeWrapper<ResolversInterfaceTypes<ResolversTypes>['PagePayload']>;
  PhoneNumber: ResolverTypeWrapper<t.Scalars['PhoneNumber']['output']>;
  Plan: ResolverTypeWrapper<t.Plan>;
  PlanPermission: ResolverTypeWrapper<t.PlanPermission>;
  PlansPayload: ResolverTypeWrapper<t.PlansPayload>;
  Portfolio: ResolverTypeWrapper<t.Portfolio>;
  PortfolioFund: ResolverTypeWrapper<t.PortfolioFund>;
  PortfolioFundsInput: t.PortfolioFundsInput;
  PortfolioFundsPayload: ResolverTypeWrapper<t.PortfolioFundsPayload>;
  PortfolioStock: ResolverTypeWrapper<t.PortfolioStock>;
  PortfolioStocksInput: t.PortfolioStocksInput;
  PortfolioStocksPayload: ResolverTypeWrapper<t.PortfolioStocksPayload>;
  Query: ResolverTypeWrapper<undefined>;
  ResendCodeInput: t.ResendCodeInput;
  ResetPasswordInput: t.ResetPasswordInput;
  SignInInput: t.SignInInput;
  SignUpInput: t.SignUpInput;
  Stock: ResolverTypeWrapper<t.Stock>;
  StocksInput: t.StocksInput;
  StocksPayload: ResolverTypeWrapper<t.StocksPayload>;
  String: ResolverTypeWrapper<t.Scalars['String']['output']>;
  SubscriptionPlan: t.SubscriptionPlan;
  SuccessPayload: ResolverTypeWrapper<t.SuccessPayload>;
  URL: ResolverTypeWrapper<t.Scalars['URL']['output']>;
  UpdateFieldInput: t.UpdateFieldInput;
  UpdateFundInput: t.UpdateFundInput;
  UpdatePortfolioFundInput: t.UpdatePortfolioFundInput;
  UpdatePortfolioInput: t.UpdatePortfolioInput;
  UpdatePortfolioStockInput: t.UpdatePortfolioStockInput;
  UpdateStockInput: t.UpdateStockInput;
  User: ResolverTypeWrapper<t.User>;
  UserRole: t.UserRole;
  UserStatus: t.UserStatus;
  VerifyCodeInput: t.VerifyCodeInput;
  Void: ResolverTypeWrapper<t.Scalars['Void']['output']>;
};

/** Mapping between all available schema types and the resolvers parents */
export type ResolversParentTypes = {
  BigInt: t.Scalars['BigInt']['output'];
  Boolean: t.Scalars['Boolean']['output'];
  Code: t.Code;
  CreateFieldInput: t.CreateFieldInput;
  CreateFundInput: t.CreateFundInput;
  CreatePortfolioFundInput: t.CreatePortfolioFundInput;
  CreatePortfolioInput: t.CreatePortfolioInput;
  CreatePortfolioStockInput: t.CreatePortfolioStockInput;
  CreateStockInput: t.CreateStockInput;
  Date: t.Scalars['Date']['output'];
  DateTime: t.Scalars['DateTime']['output'];
  DeleteFieldInput: t.DeleteFieldInput;
  DeleteFundInput: t.DeleteFundInput;
  DeletePortfolioFundInput: t.DeletePortfolioFundInput;
  DeletePortfolioInput: t.DeletePortfolioInput;
  DeletePortfolioStockInput: t.DeletePortfolioStockInput;
  DeleteStockInput: t.DeleteStockInput;
  EmailAddress: t.Scalars['EmailAddress']['output'];
  Field: t.Field;
  FieldsInput: t.FieldsInput;
  Float: t.Scalars['Float']['output'];
  ForgotPasswordInput: t.ForgotPasswordInput;
  Fund: t.Fund;
  FundsInput: t.FundsInput;
  FundsPayload: t.FundsPayload;
  ID: t.Scalars['ID']['output'];
  Int: t.Scalars['Int']['output'];
  JWT: t.Scalars['JWT']['output'];
  Json: t.Scalars['Json']['output'];
  JsonObject: t.Scalars['JsonObject']['output'];
  Membership: t.Membership;
  Mutation: undefined;
  Node: ResolversInterfaceTypes<ResolversParentTypes>['Node'];
  NonEmptyString: t.Scalars['NonEmptyString']['output'];
  PageInfo: t.PageInfo;
  PageInput: t.PageInput;
  PagePayload: ResolversInterfaceTypes<ResolversParentTypes>['PagePayload'];
  PhoneNumber: t.Scalars['PhoneNumber']['output'];
  Plan: t.Plan;
  PlanPermission: t.PlanPermission;
  PlansPayload: t.PlansPayload;
  Portfolio: t.Portfolio;
  PortfolioFund: t.PortfolioFund;
  PortfolioFundsInput: t.PortfolioFundsInput;
  PortfolioFundsPayload: t.PortfolioFundsPayload;
  PortfolioStock: t.PortfolioStock;
  PortfolioStocksInput: t.PortfolioStocksInput;
  PortfolioStocksPayload: t.PortfolioStocksPayload;
  Query: undefined;
  ResendCodeInput: t.ResendCodeInput;
  ResetPasswordInput: t.ResetPasswordInput;
  SignInInput: t.SignInInput;
  SignUpInput: t.SignUpInput;
  Stock: t.Stock;
  StocksInput: t.StocksInput;
  StocksPayload: t.StocksPayload;
  String: t.Scalars['String']['output'];
  SuccessPayload: t.SuccessPayload;
  URL: t.Scalars['URL']['output'];
  UpdateFieldInput: t.UpdateFieldInput;
  UpdateFundInput: t.UpdateFundInput;
  UpdatePortfolioFundInput: t.UpdatePortfolioFundInput;
  UpdatePortfolioInput: t.UpdatePortfolioInput;
  UpdatePortfolioStockInput: t.UpdatePortfolioStockInput;
  UpdateStockInput: t.UpdateStockInput;
  User: t.User;
  VerifyCodeInput: t.VerifyCodeInput;
  Void: t.Scalars['Void']['output'];
};

export interface BigIntScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['BigInt'], any> {
  name: 'BigInt';
}

export type CodeResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Code'] = ResolversParentTypes['Code']> = {
  code?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  expireAt?: Resolver<t.Maybe<ResolversTypes['DateTime']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  user?: Resolver<ResolversTypes['User'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export interface DateScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['Date'], any> {
  name: 'Date';
}

export interface DateTimeScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['DateTime'], any> {
  name: 'DateTime';
}

export interface EmailAddressScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['EmailAddress'], any> {
  name: 'EmailAddress';
}

export type FieldResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Field'] = ResolversParentTypes['Field']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  portfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  value?: Resolver<ResolversTypes['JsonObject'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type FundResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Fund'] = ResolversParentTypes['Fund']> = {
  category?: Resolver<t.Maybe<ResolversTypes['FundCategory']>, ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  description?: Resolver<t.Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  lastNav?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  plan?: Resolver<t.Maybe<ResolversTypes['FundPlan']>, ParentType, ContextType>;
  symbol1?: Resolver<t.Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  symbol2?: Resolver<t.Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  type?: Resolver<t.Maybe<ResolversTypes['FundType']>, ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type FundsPayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['FundsPayload'] = ResolversParentTypes['FundsPayload']> = {
  nodes?: Resolver<ReadonlyArray<ResolversTypes['Fund']>, ParentType, ContextType>;
  pageInfo?: Resolver<ResolversTypes['PageInfo'], ParentType, ContextType>;
  total?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export interface JwtScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['JWT'], any> {
  name: 'JWT';
}

export interface JsonScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['Json'], any> {
  name: 'Json';
}

export interface JsonObjectScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['JsonObject'], any> {
  name: 'JsonObject';
}

export type MembershipResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Membership'] = ResolversParentTypes['Membership']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  portfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType>;
  role?: Resolver<ResolversTypes['UserRole'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  user?: Resolver<ResolversTypes['User'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type MutationResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Mutation'] = ResolversParentTypes['Mutation']> = {
  createField?: Resolver<ResolversTypes['Field'], ParentType, ContextType, RequireFields<t.MutationCreateFieldArgs, 'input'>>;
  createFund?: Resolver<ResolversTypes['Fund'], ParentType, ContextType, RequireFields<t.MutationCreateFundArgs, 'input'>>;
  createPortfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType, RequireFields<t.MutationCreatePortfolioArgs, 'input'>>;
  createPortfolioFund?: Resolver<ResolversTypes['PortfolioFund'], ParentType, ContextType, RequireFields<t.MutationCreatePortfolioFundArgs, 'input'>>;
  createPortfolioStock?: Resolver<ResolversTypes['PortfolioStock'], ParentType, ContextType, RequireFields<t.MutationCreatePortfolioStockArgs, 'input'>>;
  createStock?: Resolver<ResolversTypes['Stock'], ParentType, ContextType, RequireFields<t.MutationCreateStockArgs, 'input'>>;
  deleteField?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationDeleteFieldArgs, 'input'>>;
  deleteFund?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationDeleteFundArgs, 'input'>>;
  deletePortfolio?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationDeletePortfolioArgs, 'input'>>;
  deletePortfolioFund?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationDeletePortfolioFundArgs, 'input'>>;
  deletePortfolioStock?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationDeletePortfolioStockArgs, 'input'>>;
  deleteStock?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationDeleteStockArgs, 'input'>>;
  forgotPassword?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationForgotPasswordArgs, 'input'>>;
  resendCode?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationResendCodeArgs, 'input'>>;
  resetPassword?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationResetPasswordArgs, 'input'>>;
  signIn?: Resolver<ResolversTypes['User'], ParentType, ContextType, RequireFields<t.MutationSignInArgs, 'input'>>;
  signUp?: Resolver<ResolversTypes['User'], ParentType, ContextType, RequireFields<t.MutationSignUpArgs, 'input'>>;
  updateField?: Resolver<ResolversTypes['Field'], ParentType, ContextType, RequireFields<t.MutationUpdateFieldArgs, 'input'>>;
  updateFund?: Resolver<ResolversTypes['Fund'], ParentType, ContextType, RequireFields<t.MutationUpdateFundArgs, 'input'>>;
  updatePortfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType, RequireFields<t.MutationUpdatePortfolioArgs, 'input'>>;
  updatePortfolioFund?: Resolver<ResolversTypes['PortfolioFund'], ParentType, ContextType, RequireFields<t.MutationUpdatePortfolioFundArgs, 'input'>>;
  updatePortfolioStock?: Resolver<ResolversTypes['PortfolioStock'], ParentType, ContextType, RequireFields<t.MutationUpdatePortfolioStockArgs, 'input'>>;
  updateStock?: Resolver<ResolversTypes['Stock'], ParentType, ContextType, RequireFields<t.MutationUpdateStockArgs, 'input'>>;
  verifyCode?: Resolver<ResolversTypes['SuccessPayload'], ParentType, ContextType, RequireFields<t.MutationVerifyCodeArgs, 'input'>>;
};

export type NodeResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Node'] = ResolversParentTypes['Node']> = {
  __resolveType: TypeResolveFn<'Code' | 'Field' | 'Fund' | 'Membership' | 'Portfolio' | 'PortfolioFund' | 'PortfolioStock' | 'Stock' | 'User', ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
};

export interface NonEmptyStringScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['NonEmptyString'], any> {
  name: 'NonEmptyString';
}

export type PageInfoResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PageInfo'] = ResolversParentTypes['PageInfo']> = {
  endCursor?: Resolver<t.Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  hasNextPage?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  hasPreviousPage?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  startCursor?: Resolver<t.Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PagePayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PagePayload'] = ResolversParentTypes['PagePayload']> = {
  __resolveType: TypeResolveFn<'FundsPayload' | 'PortfolioFundsPayload' | 'PortfolioStocksPayload' | 'StocksPayload', ParentType, ContextType>;
  nodes?: Resolver<ReadonlyArray<ResolversTypes['Node']>, ParentType, ContextType>;
  pageInfo?: Resolver<ResolversTypes['PageInfo'], ParentType, ContextType>;
  total?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
};

export interface PhoneNumberScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['PhoneNumber'], any> {
  name: 'PhoneNumber';
}

export type PlanResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Plan'] = ResolversParentTypes['Plan']> = {
  description?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  features?: Resolver<ReadonlyArray<ResolversTypes['NonEmptyString']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['SubscriptionPlan'], ParentType, ContextType>;
  monthlyPrice?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  popular?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  title?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  yearlyPrice?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PlanPermissionResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PlanPermission'] = ResolversParentTypes['PlanPermission']> = {
  familyMembers?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  funds?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['SubscriptionPlan'], ParentType, ContextType>;
  portfolios?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  schemes?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  stocks?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  uploadFiles?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PlansPayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PlansPayload'] = ResolversParentTypes['PlansPayload']> = {
  planPermissions?: Resolver<ReadonlyArray<ResolversTypes['PlanPermission']>, ParentType, ContextType>;
  plans?: Resolver<ReadonlyArray<ResolversTypes['Plan']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PortfolioResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Portfolio'] = ResolversParentTypes['Portfolio']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  description?: Resolver<t.Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  funds?: Resolver<ReadonlyArray<ResolversTypes['PortfolioFund']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  members?: Resolver<ReadonlyArray<ResolversTypes['Membership']>, ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  stocks?: Resolver<ReadonlyArray<ResolversTypes['PortfolioStock']>, ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PortfolioFundResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PortfolioFund'] = ResolversParentTypes['PortfolioFund']> = {
  cost?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  fund?: Resolver<ResolversTypes['Fund'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  portfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType>;
  units?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PortfolioFundsPayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PortfolioFundsPayload'] = ResolversParentTypes['PortfolioFundsPayload']> = {
  nodes?: Resolver<ReadonlyArray<ResolversTypes['PortfolioFund']>, ParentType, ContextType>;
  pageInfo?: Resolver<ResolversTypes['PageInfo'], ParentType, ContextType>;
  total?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PortfolioStockResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PortfolioStock'] = ResolversParentTypes['PortfolioStock']> = {
  cost?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  portfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType>;
  stock?: Resolver<ResolversTypes['Stock'], ParentType, ContextType>;
  units?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PortfolioStocksPayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PortfolioStocksPayload'] = ResolversParentTypes['PortfolioStocksPayload']> = {
  nodes?: Resolver<ReadonlyArray<ResolversTypes['PortfolioStock']>, ParentType, ContextType>;
  pageInfo?: Resolver<ResolversTypes['PageInfo'], ParentType, ContextType>;
  total?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type QueryResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  field?: Resolver<ResolversTypes['Field'], ParentType, ContextType, RequireFields<t.QueryFieldArgs, 'fieldId'>>;
  fields?: Resolver<ReadonlyArray<ResolversTypes['Field']>, ParentType, ContextType, RequireFields<t.QueryFieldsArgs, 'input'>>;
  fund?: Resolver<ResolversTypes['Fund'], ParentType, ContextType, RequireFields<t.QueryFundArgs, 'fundId'>>;
  funds?: Resolver<ResolversTypes['FundsPayload'], ParentType, ContextType, Partial<t.QueryFundsArgs>>;
  me?: Resolver<t.Maybe<ResolversTypes['User']>, ParentType, ContextType>;
  plans?: Resolver<ResolversTypes['PlansPayload'], ParentType, ContextType>;
  portfolio?: Resolver<ResolversTypes['Portfolio'], ParentType, ContextType, RequireFields<t.QueryPortfolioArgs, 'portfolioId'>>;
  portfolioFund?: Resolver<ResolversTypes['PortfolioFund'], ParentType, ContextType, RequireFields<t.QueryPortfolioFundArgs, 'portfolioFundId'>>;
  portfolioFunds?: Resolver<ResolversTypes['PortfolioFundsPayload'], ParentType, ContextType, RequireFields<t.QueryPortfolioFundsArgs, 'input'>>;
  portfolioStock?: Resolver<ResolversTypes['PortfolioStock'], ParentType, ContextType, RequireFields<t.QueryPortfolioStockArgs, 'portfolioStockId'>>;
  portfolioStocks?: Resolver<ResolversTypes['PortfolioStocksPayload'], ParentType, ContextType, RequireFields<t.QueryPortfolioStocksArgs, 'input'>>;
  stock?: Resolver<ResolversTypes['Stock'], ParentType, ContextType, RequireFields<t.QueryStockArgs, 'stockId'>>;
  stocks?: Resolver<ResolversTypes['StocksPayload'], ParentType, ContextType, Partial<t.QueryStocksArgs>>;
};

export type StockResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Stock'] = ResolversParentTypes['Stock']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  exchange?: Resolver<ResolversTypes['Exchange'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  lastPrice?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  symbol?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type StocksPayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['StocksPayload'] = ResolversParentTypes['StocksPayload']> = {
  nodes?: Resolver<ReadonlyArray<ResolversTypes['Stock']>, ParentType, ContextType>;
  pageInfo?: Resolver<ResolversTypes['PageInfo'], ParentType, ContextType>;
  total?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type SuccessPayloadResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['SuccessPayload'] = ResolversParentTypes['SuccessPayload']> = {
  error?: Resolver<t.Maybe<ResolversTypes['ErrorCode']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export interface UrlScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['URL'], any> {
  name: 'URL';
}

export type UserResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['User'] = ResolversParentTypes['User']> = {
  codes?: Resolver<ReadonlyArray<ResolversTypes['Code']>, ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  firstName?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  isBlocked?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  isVerified?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  lastName?: Resolver<t.Maybe<ResolversTypes['NonEmptyString']>, ParentType, ContextType>;
  memberships?: Resolver<ReadonlyArray<ResolversTypes['Membership']>, ParentType, ContextType>;
  mobile?: Resolver<ResolversTypes['PhoneNumber'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  password?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  salt?: Resolver<ResolversTypes['NonEmptyString'], ParentType, ContextType>;
  status?: Resolver<ResolversTypes['UserStatus'], ParentType, ContextType>;
  token?: Resolver<ResolversTypes['JWT'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export interface VoidScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['Void'], any> {
  name: 'Void';
}

export type Resolvers<ContextType = GraphQLContext> = {
  BigInt?: GraphQLScalarType;
  Code?: CodeResolvers<ContextType>;
  Date?: GraphQLScalarType;
  DateTime?: GraphQLScalarType;
  EmailAddress?: GraphQLScalarType;
  Field?: FieldResolvers<ContextType>;
  Fund?: FundResolvers<ContextType>;
  FundsPayload?: FundsPayloadResolvers<ContextType>;
  JWT?: GraphQLScalarType;
  Json?: GraphQLScalarType;
  JsonObject?: GraphQLScalarType;
  Membership?: MembershipResolvers<ContextType>;
  Mutation?: MutationResolvers<ContextType>;
  Node?: NodeResolvers<ContextType>;
  NonEmptyString?: GraphQLScalarType;
  PageInfo?: PageInfoResolvers<ContextType>;
  PagePayload?: PagePayloadResolvers<ContextType>;
  PhoneNumber?: GraphQLScalarType;
  Plan?: PlanResolvers<ContextType>;
  PlanPermission?: PlanPermissionResolvers<ContextType>;
  PlansPayload?: PlansPayloadResolvers<ContextType>;
  Portfolio?: PortfolioResolvers<ContextType>;
  PortfolioFund?: PortfolioFundResolvers<ContextType>;
  PortfolioFundsPayload?: PortfolioFundsPayloadResolvers<ContextType>;
  PortfolioStock?: PortfolioStockResolvers<ContextType>;
  PortfolioStocksPayload?: PortfolioStocksPayloadResolvers<ContextType>;
  Query?: QueryResolvers<ContextType>;
  Stock?: StockResolvers<ContextType>;
  StocksPayload?: StocksPayloadResolvers<ContextType>;
  SuccessPayload?: SuccessPayloadResolvers<ContextType>;
  URL?: GraphQLScalarType;
  User?: UserResolvers<ContextType>;
  Void?: GraphQLScalarType;
};

