/*
  Warnings:

  - The `plan` column on the `Fund` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The `type` column on the `Fund` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The `category` column on the `Fund` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- CreateEnum
CREATE TYPE "FundPlan" AS ENUM ('Direct', 'Regular');

-- CreateEnum
CREATE TYPE "FundType" AS ENUM ('BONUS', 'GROWTH', 'IDCW', 'IDCW_PAYOUT', 'IDCW_REINVESTMENT', 'IDCW_DAILY_PAYOUT', 'IDCW_DAILY_REINVESTMENT', 'IDCW_WEEKLY_PAYOUT', 'IDCW_WEEKLY_REINVESTMENT', 'IDCW_MONTHLY_PAYOUT', 'IDCW_MONTHLY_REINVESTMENT', 'IDCW_QUARTERLY_PAYOUT', 'IDCW_QUARTERLY_REINVESTMENT', 'IDCW_HALFYEARLY_PAYOUT', 'IDCW_HALFYEARLY_REINVESTMENT', 'IDCW_YEARLY_PAYOUT', 'IDCW_YEARLY_REINVESTMENT');

-- CreateEnum
CREATE TYPE "FundCategory" AS ENUM ('HYBRID_DYNAMIC_ASSET_ALLOCATION', 'HYBRID_MULTI_ASSET_ALLOCATION', 'HYBRID_ARBITRAGE', 'HYBRID_AGGRESSIVE', 'HYBRID_CONSERVATIVE', 'HYBRID_EQUITY_SAVINGS', 'EQUITY_ELSS', 'EQUITY_FOCUSED', 'EQUITY_DIVIDEND_YIELD', 'EQUITY_BANKING_AND_FINANCIAL_SERVICES', 'EQUITY_SECTORAL_TECHNOLOGY', 'EQUITY_SECTORAL_INFRASTRUCTURE', 'EQUITY_SECTORAL_PHARMA_AND_HEALTHCARE', 'EQUITY_THEMATIC_CONSUMPTION', 'EQUITY_THEMATIC_INTERNATIONAL', 'EQUITY_THEMATIC_MANUFACTURING', 'EQUITY_THEMATIC_TRANSPORTATION', 'EQUITY_THEMATIC_MNC', 'EQUITY_THEMATIC_PSU', 'EQUITY_THEMATIC_QUANTITATIVE', 'EQUITY_THEMATIC_ESG', 'EQUITY_THEMATIC_OTHERS', 'EQUITY_VALUE', 'EQUITY_FLEXI_CAP', 'EQUITY_LARGE_AND_MID_CAP', 'EQUITY_SMALL_CAP', 'EQUITY_MID_CAP', 'EQUITY_LARGE_CAP', 'EQUITY_MULTI_CAP', 'DEBT_DYNAMIC_BOND', 'DEBT_CORPORATE_BOND', 'DEBT_BANKING_AND_PSU', 'DEBT_LIQUID', 'DEBT_FLOATER', 'DEBT_GILT', 'DEBT_GILT_10_YEARS_CONSTANT', 'DEBT_MONEY_MARKET', 'DEBT_CREDIT_RISK', 'DEBT_MEDIUM_TO_LONG_DURATION', 'DEBT_LONG_DURATION', 'DEBT_LOW_DURATION', 'DEBT_MEDIUM_DURATION', 'DEBT_OVERNIGHT', 'DEBT_SHORT_DURATION', 'DEBT_ULTRA_SHORT_DURATION', 'FOF_DOMESTIC_DEBT', 'FOF_DOMESTIC_HYBRID', 'FOF_DOMESTIC_EQUITY', 'FOF_DOMESTIC_GOLD', 'FOF_DOMESTIC_SILVER', 'FOF_OVERSEAS', 'CHILDRENS_FUND', 'RETIREMENT_FUND', 'ETF', 'INDEX_FUND');

-- AlterTable
ALTER TABLE "Fund" DROP COLUMN "plan",
ADD COLUMN     "plan" "FundPlan" NOT NULL DEFAULT 'Direct',
DROP COLUMN "type",
ADD COLUMN     "type" "FundType",
DROP COLUMN "category",
ADD COLUMN     "category" "FundCategory";
